# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_check_update = false

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", ip: "10.10.10.10" #, adapter: "1"
  config.vm.network "public_network", use_dhcp_assigned_default_route: true

  # Enable ip forwarding and forward network from external interface to internal
  config.vm.provision "shell",
  run:"always",
  inline: <<-SHELL
    sysctl -w net.ipv4.ip_forward=1

    iptables -A FORWARD -i eth2 -o eth1 -s 10.10.10.0/24 -m conntrack --ctstate NEW -j ACCEPT
    iptables -A FORWARD -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
    iptables -A POSTROUTING -t nat -j MASQUERADE
  SHELL
end
